name: ipad_dynamic_cursor
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.14.0 <3.0.0"
dependencies:
  adaptive_dialog:
  animations:
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_localizations:
    sdk: flutter
  flutter_portal:
  font_awesome_flutter:
  freezed_annotation:
  gap:
  hooks_riverpod:
  state_notifier:
  sprung:
# Firebase
#  firebase_core:
#  firebase_auth:
#  cloud_firestore:
#  freezed_annotation:
dev_dependencies:
  build_runner:
  dart_code_metrics:
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable:
  pedantic_mono:
flutter:
  uses-material-design: true
  assets:
    - assets/images/
